export const SAVE_PRODUCTS_FULLFILLED = 'SAVE_PRODUCTS_FULLFILLED';
export const SAVE_PRODUCTS_LOADING = 'SAVE_PRODUCTS_LOADING';
export const SAVE_PRODUCTS_REJECTED = 'SAVE_PRODUCTS_REJECTED';

export const DELETE_PRODUCTS_LOADING='DELETE_PRODUCTS_LOADING';
export const DELETE_PRODUCTS_FULLFILLED='DELETE_PRODUCTS_FULLFILLED';
export const DELETE_PRODUCTS_REJECTED='DELETE_PRODUCTS_REJECTED';

export const GET_PRODUCTS_LOADING='GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_FULLFILLED='GET_PRODUCTS_FULLFILLED';
export const GET_PRODUCTS_REJECTED='GET_PRODUCTS_REJECTED';

export const POST_PRODUCTS_REJECTED='POST_PRODUCTS_REJECTED';
export const POST_PRODUCTS_LOADING='POST_PRODUCTS_LOADING';
export const POST_PRODUCTS_FULLFILLED='POST_PRODUCTS_FULLFILLED';

export const EDIT_PRODUCTS_REJECTED='EDIT_PRODUCTS_REJECTED';
export const EDIT_PRODUCTS_LOADING='EDIT_PRODUCTS_LOADING';
export const EDIT_PRODUCTS_FULLFILLED='EDIT_PRODUCTS_FULLFILLED';